 CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS"."XXWSB_SALES_TERR_V" ("TERRITORY_ID", "SALESREP_NUMBER", "NAME", "TERRITORY_DESC", "TERRITORY", "TERRITORY_FLEXFIELD", "LOB_ID", "LINE_OF_BUSINESS", "TITLE", "JOB_TITLE", "DIV", "DIVISION", "PLT", "PLANT", "TEAM_ID", "TEAM", "START_DATE_ACTIVE", "TOP_ROLLUP_ID", "TOP_ROLLUP_TEAM", "TOP_ROLLUP_NUMBER", "TOP_ROLLUP_NAME", "END_DATE_ACTIVE", "STATUS") AS 
  SELECT
RAR.TERRITORY_ID,
RAS.SALESREP_NUMBER,
RAS.NAME,
DECODE(RAR.ATTRIBUTE1,'1020','PMFG',RAR.DESCRIPTION) TERRITORY_DESC,
RAR.NAME TERRITORY,
RAR.SEGMENT1 TERRITORY_FLEXFIELD,
RAR.ATTRIBUTE1 LOB_ID,
BL.MEANING LINE_OF_BUSINESS,
RDV.ATTRIBUTE1 TITLE,
TIT.MEANING JOB_TITLE,
RDV.ATTRIBUTE2 DIV,
DIV.MEANING DIVISION,
RDV.ATTRIBUTE3 PLT,
PLT.MEANING PLANT,
TEAM.TEAM_NUMBER TEAM_ID,
TEAM.TEAM_NAME TEAM,
--RAS.SALESREP_ID,
RAT.START_DATE_ACTIVE,
(SELECT DISTINCT TM.TEAM_NUMBER
 FROM JTF_RS_TEAMS_VL TM
 WHERE TM.TEAM_NAME = TEAM.TEAM_DESC) TOP_ROLLUP_ID,
MGRR.TEAM_DESC TOP_ROLLUP_TEAM,
MGRR.SALESREP_NUMBER TOP_ROLLUP_NUMBER,
MGRR.MGR_NAME TOP_ROLLUP_NAME,
RAS.END_DATE_ACTIVE,
RAS.STATUS
FROM
(SELECT LOOKUP_CODE, MEANING FROM FND_LOOKUP_VALUES_VL WHERE LOOKUP_TYPE = 'WSB_SALESREP_TITLES' AND END_DATE_ACTIVE IS NULL AND ENABLED_FLAG = 'Y') TIT,
(SELECT LOOKUP_CODE, MEANING FROM FND_LOOKUP_VALUES_VL WHERE LOOKUP_TYPE = 'WSB_DIVISIONS' AND END_DATE_ACTIVE IS NULL AND ENABLED_FLAG = 'Y') DIV,
(SELECT LOOKUP_CODE, MEANING FROM FND_LOOKUP_VALUES_VL WHERE LOOKUP_TYPE = 'WSB_PLANTS' AND END_DATE_ACTIVE IS NULL AND ENABLED_FLAG = 'Y') PLT,
(SELECT LOOKUP_CODE, MEANING FROM FND_LOOKUP_VALUES_VL WHERE LOOKUP_TYPE = 'WSB_LINE_OF_BUSINESS' AND END_DATE_ACTIVE IS NULL AND ENABLED_FLAG = 'Y') BL,
(
    SELECT
    TERRITORY_ID,
    SALESREP_ID,
    START_DATE_ACTIVE,
    END_DATE_ACTIVE
    FROM
    APPS.RA_SALESREP_TERRITORIES
    WHERE
    (END_DATE_ACTIVE IS NULL OR END_DATE_ACTIVE >= SYSDATE)
) RAT,
(
    SELECT JRS.SALESREP_ID,
           RES.RESOURCE_NAME NAME,
           JRS.SALESREP_NUMBER,
           JRS.STATUS,
           RES.END_DATE_ACTIVE
      FROM JTF_RS_SALESREPS JRS, JTF_RS_RESOURCE_EXTNS_VL RES
     WHERE JRS.RESOURCE_ID = RES.RESOURCE_ID
           AND JRS.ORG_ID = '0'
           AND RES.CATEGORY IN ('EMPLOYEE',
                                'OTHER',
                                'PARTY',
                                'PARTNER',
                                'SUPPLIER_CONTACT')
) RAS,
APPS.RA_TERRITORIES RAR,
(
    SELECT rsc.ATTRIBUTE1,
           rsc.ATTRIBUTE2,
           rsc.ATTRIBUTE3,
           rsc.ATTRIBUTE4,
           rsc.ATTRIBUTE5,
           rsc.ATTRIBUTE6,
           rsc.ATTRIBUTE7,
           rsc.ATTRIBUTE8,
           rsc.ATTRIBUTE9,
           rsc.ATTRIBUTE10,
           rsc.ATTRIBUTE11,
           rsc.ATTRIBUTE12,
           rsc.ATTRIBUTE13,
           rsc.ATTRIBUTE14,
           rsc.ATTRIBUTE15,
           srp.SALESREP_NUMBER
      FROM JTF_RS_RESOURCE_EXTNS_VL rsc, JTF_OBJECTS_VL obj, JTF_RS_SALESREPS srp
     WHERE     rsc.category = obj.object_code
           AND SRP.ORG_ID = '0'
           AND rsc.resource_id = srp.resource_id(+)
) RDV,
(
    SELECT
    JRT.TEAM_NUMBER,
    JRT.TEAM_NAME,
    JRT.TEAM_DESC,
    JRT.END_DATE_ACTIVE TEAM_END_DATE,
    JRTM.TEAM_MEMBER_ID,
    JRTM.TEAM_ID,
    JRTM.RESOURCE_TYPE,
    RAS.PERSON_ID,
    JRTM.CATEGORY,
    JRTM.CATEGORY_NAME,
    RAS.RESOURCE_NUMBER,
    RAS.NAME,
    RAS.RESOURCE_ID,
    RAS.SALESREP_NUMBER,
    RAS.SALESREP_ID,
    RAS.END_DATE_ACTIVE RESOURCE_END_DATE,
    RAS.GROUP_NAME, RAS.GROUP_DESC
    FROM
    (
         SELECT     JRS.SALESREP_ID,
               RES.RESOURCE_NAME NAME,
               JRS.SALESREP_NUMBER,
               JRS.STATUS,
               RES.RESOURCE_NUMBER,
               RES.RESOURCE_ID,
               JRS.END_DATE_ACTIVE,
               JRS.STATUS,
               JRG.GROUP_NUMBER,
               JRG.GROUP_NAME,
               JRG.GROUP_DESC,
               JRGM.PERSON_ID,
               RES_RL_END_DATE
          FROM JTF_RS_SALESREPS JRS,
               JTF_RS_RESOURCE_EXTNS_VL RES,
               jtf_rs_groups_vl JRG,
               jtf_rs_group_members_vl JRGM,
               (
                    SELECT JR.GROUP_NAME, JRG.GROUP_ID, JRG.RESOURCE_ID, JRG.RESOURCE_NAME, JRD_V.RES_RL_START_DATE, JRD_V.RES_RL_END_DATE, JRD_V.ROLE_TYPE_NAME, JRD_V.ROLE_NAME
                    FROM
                    jtf_rs_groups_vl JR,
                    jtf_rs_group_members_vl JRG,
                    JTF_RS_DEFRESROLES_VL JRD_V
                    WHERE
                        JRG.GROUP_ID = JR.GROUP_ID
                    AND JRG.DELETE_FLAG = 'N'
                    AND
                        JRD_V.ROLE_RESOURCE_ID = JRG.GROUP_MEMBER_ID  -- THE GROUP MEMBER
                    AND JRD_V.ROLE_RESOURCE_TYPE = 'RS_GROUP_MEMBER'
                    AND JRD_V.ROLE_NAME = 'Sales Group Reporting'
                    AND JRD_V.DELETE_FLAG = 'N'
               ) GRP_ROLE
         WHERE --JRS.RESOURCE_ID = 100002817 AND
               JRS.RESOURCE_ID = RES.RESOURCE_ID
               AND JRS.ORG_ID = 0
               AND RES.CATEGORY IN ('EMPLOYEE',
                                    'OTHER',
                                    'PARTY',
                                    'PARTNER',
                                    'SUPPLIER_CONTACT')
               AND
                   RES.RESOURCE_NUMBER = JRGM.RESOURCE_NUMBER  -- GROUP RESOURCES
               AND JRGM.GROUP_ID = JRG.GROUP_ID  -- GROUP
               AND (JRGM.DELETE_FLAG = 'N' OR JRGM.DELETE_FLAG IS NULL)  -- EXCLUDE DELETED RESOURCES
               AND
                   JRGM.RESOURCE_ID = GRP_ROLE.RESOURCE_ID
               AND JRGM.GROUP_ID = GRP_ROLE.GROUP_ID
    ) RAS,
    JTF_RS_TEAMS_VL JRT,
    JTF_RS_TEAM_MEMBERS_VL JRTM
    WHERE
        RAS.GROUP_NUMBER = JRTM.RESOURCE_NUMBER
    AND JRTM.RESOURCE_TYPE = 'GROUP'
    AND
        JRTM.TEAM_ID = JRT.TEAM_ID
    AND (JRTM.DELETE_FLAG = 'N' OR JRTM.DELETE_FLAG IS NULL)
    UNION
    -- Query Teams/members (RESOURCE_TYPE = "INDIVIDUAL")
    SELECT
    JRT.TEAM_NUMBER,
    JRT.TEAM_NAME,
    JRT.TEAM_DESC,
    JRT.END_DATE_ACTIVE TEAM_END_DATE,
    JRTM.TEAM_MEMBER_ID,
    JRTM.TEAM_ID,
    JRTM.RESOURCE_TYPE,
    JRTM.PERSON_ID,
    JRTM.CATEGORY,
    JRTM.CATEGORY_NAME,
    JRTM.RESOURCE_NUMBER,
    RAS.NAME,
    RAS.RESOURCE_ID,
    RAS.SALESREP_NUMBER,
    RAS.SALESREP_ID,
    RAS.END_DATE_ACTIVE RESOURCE_END_DATE,
    NULL "GROUP_NAME",
    NULL "GROUP_DESC"
    FROM
    JTF_RS_TEAMS_VL JRT,
    JTF_RS_TEAM_MEMBERS_VL JRTM,
    (
        SELECT JRS.SALESREP_ID,
               RES.RESOURCE_NAME NAME,
               JRS.SALESREP_NUMBER,
               JRS.STATUS,
               RES.RESOURCE_NUMBER,
               RES.RESOURCE_ID,
               JRS.END_DATE_ACTIVE,
               JRS.STATUS
          FROM JTF_RS_SALESREPS JRS, JTF_RS_RESOURCE_EXTNS_VL RES
         WHERE JRS.RESOURCE_ID = RES.RESOURCE_ID
               AND JRS.ORG_ID = 0
               AND RES.CATEGORY IN ('EMPLOYEE',
                                    'OTHER',
                                    'PARTY',
                                    'PARTNER',
                                    'SUPPLIER_CONTACT')
    ) RAS
    WHERE
        RAS.RESOURCE_NUMBER = JRTM.RESOURCE_NUMBER
    AND JRTM.RESOURCE_TYPE = 'INDIVIDUAL'
    AND
        JRTM.TEAM_ID = JRT.TEAM_ID
    AND (JRTM.DELETE_FLAG = 'N' OR JRTM.DELETE_FLAG IS NULL)
) TEAM,
(
    SELECT
    JRT.TEAM_NUMBER,
    JRT.TEAM_NAME,
    JRT.TEAM_DESC,
    RAS.SALESREP_NUMBER,
    RAS.NAME MGR_NAME
    FROM
    JTF_RS_TEAMS_VL JRT,
    (
        SELECT DISTINCT JRS.SALESREP_ID,
               UPPER(PAP.FIRST_NAME)||' '||UPPER(PAP.LAST_NAME) NAME,
               JRS.SALESREP_NUMBER,
               JRS.STATUS
          FROM JTF_RS_SALESREPS JRS, JTF_RS_RESOURCE_EXTNS_VL RES, PER_ALL_PEOPLE_F PAP
         WHERE JRS.RESOURCE_ID = RES.RESOURCE_ID
               AND JRS.ORG_ID = '0'
               AND RES.CATEGORY IN ('EMPLOYEE',
                                    'OTHER',
                                    'PARTY',
                                    'PARTNER',
                                    'SUPPLIER_CONTACT')
               AND JRS.PERSON_ID = PAP.PERSON_ID (+)
    ) RAS
    WHERE
        JRT.ATTRIBUTE1 = RAS.SALESREP_NUMBER (+)
    AND (JRT.END_DATE_ACTIVE IS NULL OR JRT.END_DATE_ACTIVE > TRUNC(SYSDATE))
) MGRR
WHERE
    RAS.SALESREP_ID = RAT.SALESREP_ID (+)
AND RAT.TERRITORY_ID = RAR.TERRITORY_ID (+)
AND
    RAR.ATTRIBUTE1 = BL.LOOKUP_CODE (+)
AND
    RAS.SALESREP_NUMBER = RDV.SALESREP_NUMBER (+)
AND
    RDV.ATTRIBUTE1 = TIT.LOOKUP_CODE (+)
AND RDV.ATTRIBUTE2 = DIV.LOOKUP_CODE (+)
AND RDV.ATTRIBUTE3 = PLT.LOOKUP_CODE (+)
AND
    RAS.SALESREP_NUMBER = TEAM.SALESREP_NUMBER (+)
AND TEAM.TEAM_NUMBER = MGRR.TEAM_NUMBER (+)
;


  GRANT SELECT ON "APPS"."XXWSB_SALES_TERR_V" TO "APPSRO";