SELECT
RAS.SALESREP_ID,
RAS.SALESREP_NUMBER SALES_REP_NUMBER,
RAS.NAME SALES_REP,
RAS.EMAIL_ADDRESS,
(
   SELECT TIT.MEANING
   FROM JTF_RS_RESOURCE_EXTNS_VL JR, FND_LOOKUP_VALUES TIT
   WHERE JR.RESOURCE_ID = RAS.RESOURCE_ID AND JR.ATTRIBUTE1 = TIT.LOOKUP_CODE
   AND TIT.END_DATE_ACTIVE IS NULL AND TIT.ENABLED_FLAG = 'Y' AND TIT.LOOKUP_TYPE = 'WSB_SALESREP_TITLES'
) TITLE,
JRT.TEAM_NAME TEAM,
Substr(BOLINF.WSB_SALESREP_TEAM_INFO.WSB_TEAM_LOB_NAME(RAS.SALESREP_ID), 1, Instr(BOLINF.WSB_SALESREP_TEAM_INFO.WSB_TEAM_LOB_NAME(RAS.SALESREP_ID), '|')-1) ROLLUP_TEAM,
(
   SELECT DISTINCT PAP.FIRST_NAME||' '||PAP.LAST_NAME TEAM_MANAGER
   FROM PER_ALL_PEOPLE_F PAP, JTF_RS_SALESREPS RS
   WHERE RS.SALESREP_NUMBER = JRT.ATTRIBUTE1
   AND PAP.PERSON_ID = RS.PERSON_ID
) "MANAGER",
RAS.PERSON_ID
FROM
(
    SELECT     JRS.SALESREP_ID,
          RES.RESOURCE_NAME NAME,
          JRS.SALESREP_NUMBER,
          JRS.STATUS,
          RES.RESOURCE_NUMBER,
          RES.RESOURCE_ID,
          JRS.END_DATE_ACTIVE,
          JRS.STATUS,
          JRG.GROUP_NUMBER,
          JRG.GROUP_NAME,
          JRG.GROUP_DESC,
          JRGM.PERSON_ID,
          RES_RL_END_DATE,
          JRS.EMAIL_ADDRESS
     FROM JTF_RS_SALESREPS JRS,
          JTF_RS_RESOURCE_EXTNS_VL RES,
          jtf_rs_groups_vl JRG,
          jtf_rs_group_members_vl JRGM,
          (
               SELECT JR.GROUP_NAME, JRG.GROUP_ID, JRG.RESOURCE_ID, JRG.RESOURCE_NAME, JRD_V.RES_RL_START_DATE, JRD_V.RES_RL_END_DATE, JRD_V.ROLE_TYPE_NAME, JRD_V.ROLE_NAME
               FROM
               jtf_rs_groups_vl JR,
               jtf_rs_group_members_vl JRG,
               JTF_RS_DEFRESROLES_VL JRD_V
               WHERE
                   JRG.GROUP_ID = JR.GROUP_ID
               AND JRG.DELETE_FLAG = 'N'
               AND
                   JRD_V.ROLE_RESOURCE_ID = JRG.GROUP_MEMBER_ID  -- THE GROUP MEMBER
               AND JRD_V.ROLE_RESOURCE_TYPE = 'RS_GROUP_MEMBER'
               AND JRD_V.ROLE_NAME = 'Sales Group Reporting'
               AND JRD_V.DELETE_FLAG = 'N'
          ) GRP_ROLE
    WHERE     JRS.RESOURCE_ID = RES.RESOURCE_ID
          AND JRS.ORG_ID = 0
          AND RES.CATEGORY IN ('EMPLOYEE',
                               'OTHER',
                               'PARTY',
                               'PARTNER',
                               'SUPPLIER_CONTACT')
          AND
              RES.RESOURCE_NUMBER = JRGM.RESOURCE_NUMBER  -- GROUP RESOURCES
          AND JRGM.GROUP_ID = JRG.GROUP_ID  -- GROUP
          AND (JRGM.DELETE_FLAG = 'N' OR JRGM.DELETE_FLAG IS NULL)  -- EXCLUDE DELETED RESOURCES
          AND
              JRGM.RESOURCE_ID = GRP_ROLE.RESOURCE_ID
          AND JRGM.GROUP_ID = GRP_ROLE.GROUP_ID
) RAS,
JTF_RS_TEAMS_VL JRT,
JTF_RS_TEAM_MEMBERS_VL JRTM
WHERE
   RAS.GROUP_NUMBER = JRTM.RESOURCE_NUMBER
AND JRTM.RESOURCE_TYPE = 'GROUP'
AND
   JRTM.TEAM_ID = JRT.TEAM_ID
AND (JRTM.DELETE_FLAG = 'N' OR JRTM.DELETE_FLAG IS NULL)
GROUP BY
RAS.SALESREP_ID,
RAS.SALESREP_NUMBER,
RAS.NAME,
RAS.EMAIL_ADDRESS,
RAS.RESOURCE_ID,
JRT.TEAM_NAME,
JRT.ATTRIBUTE1,
RAS.PERSON_ID
UNION
-- Query Teams/members (RESOURCE_TYPE = "INDIVIDUAL")
SELECT
RAS.SALESREP_ID,
RAS.SALESREP_NUMBER,
RAS.NAME,
RAS.EMAIL_ADDRESS,
(
   SELECT TIT.MEANING
   FROM JTF_RS_RESOURCE_EXTNS_VL JR, FND_LOOKUP_VALUES TIT
   WHERE JR.RESOURCE_ID = RAS.RESOURCE_ID AND JR.ATTRIBUTE1 = TIT.LOOKUP_CODE
   AND TIT.END_DATE_ACTIVE IS NULL AND TIT.ENABLED_FLAG = 'Y' AND TIT.LOOKUP_TYPE = 'WSB_SALESREP_TITLES'
),
JRT.TEAM_NAME,
Substr(BOLINF.WSB_SALESREP_TEAM_INFO.WSB_TEAM_LOB_NAME(RAS.SALESREP_ID), 1, Instr(BOLINF.WSB_SALESREP_TEAM_INFO.WSB_TEAM_LOB_NAME(RAS.SALESREP_ID), '|')-1) ROLLUP_TEAM,
(
   SELECT DISTINCT PAP.FIRST_NAME||' '||PAP.LAST_NAME TEAM_MANAGER
   FROM PER_ALL_PEOPLE_F PAP, JTF_RS_SALESREPS RS
   WHERE RS.SALESREP_NUMBER = JRT.ATTRIBUTE1
   AND PAP.PERSON_ID = RS.PERSON_ID
),
JRTM.PERSON_ID
FROM
JTF_RS_TEAMS_VL JRT,
JTF_RS_TEAM_MEMBERS_VL JRTM,
(
   SELECT JRS.SALESREP_ID,
          RES.RESOURCE_NAME NAME,
          JRS.SALESREP_NUMBER,
          JRS.STATUS,
          RES.RESOURCE_NUMBER,
          RES.RESOURCE_ID,
          JRS.END_DATE_ACTIVE,
          JRS.STATUS,
          JRS.EMAIL_ADDRESS
     FROM JTF_RS_SALESREPS JRS, JTF_RS_RESOURCE_EXTNS_VL RES
    WHERE JRS.RESOURCE_ID = RES.RESOURCE_ID
          AND JRS.ORG_ID = 0
          AND RES.CATEGORY IN ('EMPLOYEE',
                               'OTHER',
                               'PARTY',
                               'PARTNER',
                               'SUPPLIER_CONTACT')
) RAS
WHERE
   RAS.RESOURCE_NUMBER = JRTM.RESOURCE_NUMBER
AND JRTM.RESOURCE_TYPE = 'INDIVIDUAL'
AND
   JRTM.TEAM_ID = JRT.TEAM_ID
AND (JRTM.DELETE_FLAG = 'N' OR JRTM.DELETE_FLAG IS NULL)
GROUP BY
RAS.SALESREP_ID,
RAS.SALESREP_NUMBER,
RAS.NAME,
RAS.EMAIL_ADDRESS,
RAS.RESOURCE_ID,
JRT.TEAM_NAME,
JRT.ATTRIBUTE1,
JRTM.PERSON_ID
ORDER BY 6,7
